"use client";

import { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Download, 
  Package, 
  FileCode, 
  FileJson, 
  FileText, 
  FolderTree,
  Loader2,
  Check,
  Copy,
  ExternalLink,
  Archive,
  BookOpen,
  Server,
  TestTube,
  Palette,
  ChevronRight
} from "lucide-react";
import { cn } from "@/lib/utils";
import { EnterprisePreset } from "@/lib/enterprise-presets";
import JSZip from "jszip";

interface ExportFile {
  path: string;
  name: string;
  content: string;
  type: "code" | "config" | "docs" | "api" | "test" | "style";
  icon: React.ElementType;
}

interface EnterpriseExportProps {
  projectName: string;
  generatedCode: string;
  preset: EnterprisePreset | null;
  analysis?: {
    screenInventory?: unknown;
    interactionFlows?: unknown;
    dataModel?: unknown;
    businessRules?: unknown[];
  };
  onExport?: (format: "zip" | "github") => void;
}

export function EnterpriseExport({ 
  projectName, 
  generatedCode, 
  preset, 
  analysis,
  onExport 
}: EnterpriseExportProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [exportProgress, setExportProgress] = useState(0);
  const [expandedSection, setExpandedSection] = useState<string | null>("source");
  const [copiedFile, setCopiedFile] = useState<string | null>(null);
  
  // Generate export files
  const generateExportFiles = useCallback((): ExportFile[] => {
    const files: ExportFile[] = [];
    const timestamp = new Date().toISOString();
    const presetName = preset?.name || "Auto-Detect";
    
    // 1. Getting Started
    files.push({
      path: "1-getting-started/README.md",
      name: "README.md",
      type: "docs",
      icon: BookOpen,
      content: `# ${projectName}

Generated by Replay.build - Enterprise Legacy Modernization Platform

## 📅 Generated
- Date: ${timestamp}
- Design System: ${presetName}

## 🚀 Quick Start

\`\`\`bash
# Install dependencies
npm install

# Start development server
npm run dev

# Build for production
npm run build
\`\`\`

## 📁 Package Contents

\`\`\`
├── 1-getting-started/     # This folder - start here
├── 2-source-code/         # Complete React/TypeScript codebase
├── 3-api-specifications/  # OpenAPI specs, Postman collection
├── 4-documentation/       # Technical docs, architecture
├── 5-design-system/       # Design tokens, Tailwind config
├── 6-quality-assurance/   # Test scaffolds, QA checklists
└── 7-deployment/          # Docker, CI/CD configs
\`\`\`

## 🎯 What's Included

- ✅ Production-ready React components (TypeScript strict)
- ✅ Complete API specifications (OpenAPI 3.0)
- ✅ Technical documentation with diagrams
- ✅ Business rules catalog
- ✅ Test scaffolds (unit, integration, a11y)
- ✅ Design system tokens and Tailwind config
- ✅ Deployment configurations

## 📚 Documentation

See \`4-documentation/\` for:
- Architecture overview
- Component documentation
- API integration guide
- Business logic catalog
- Deployment guide

## 🔧 Backend Integration

See \`3-api-specifications/backend-checklist.md\` for what your backend team needs to implement.

---

Generated with ❤️ by [Replay.build](https://replay.build)
`
    });
    
    // 2. Source Code
    files.push({
      path: "2-source-code/index.html",
      name: "index.html",
      type: "code",
      icon: FileCode,
      content: generatedCode
    });
    
    files.push({
      path: "2-source-code/package.json",
      name: "package.json",
      type: "config",
      icon: FileJson,
      content: JSON.stringify({
        name: projectName.toLowerCase().replace(/\s+/g, "-"),
        version: "1.0.0",
        private: true,
        scripts: {
          dev: "vite",
          build: "tsc && vite build",
          preview: "vite preview",
          lint: "eslint . --ext ts,tsx",
          test: "vitest",
          "test:ui": "vitest --ui",
          "test:coverage": "vitest --coverage"
        },
        dependencies: {
          "react": "^18.2.0",
          "react-dom": "^18.2.0",
          "@tanstack/react-query": "^5.0.0",
          "zod": "^3.22.0",
          "recharts": "^2.10.0",
          "lucide-react": "^0.300.0",
          "framer-motion": "^10.16.0",
          "clsx": "^2.0.0",
          "tailwind-merge": "^2.0.0"
        },
        devDependencies: {
          "@types/react": "^18.2.0",
          "@types/react-dom": "^18.2.0",
          "@vitejs/plugin-react": "^4.2.0",
          "autoprefixer": "^10.4.0",
          "postcss": "^8.4.0",
          "tailwindcss": "^3.4.0",
          "typescript": "^5.3.0",
          "vite": "^5.0.0",
          "vitest": "^1.0.0",
          "@testing-library/react": "^14.0.0",
          "@testing-library/jest-dom": "^6.0.0",
          "eslint": "^8.55.0",
          "@typescript-eslint/eslint-plugin": "^6.0.0",
          "@typescript-eslint/parser": "^6.0.0"
        }
      }, null, 2)
    });
    
    files.push({
      path: "2-source-code/tsconfig.json",
      name: "tsconfig.json",
      type: "config",
      icon: FileJson,
      content: JSON.stringify({
        compilerOptions: {
          target: "ES2020",
          useDefineForClassFields: true,
          lib: ["ES2020", "DOM", "DOM.Iterable"],
          module: "ESNext",
          skipLibCheck: true,
          moduleResolution: "bundler",
          allowImportingTsExtensions: true,
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: "react-jsx",
          strict: true,
          noUnusedLocals: true,
          noUnusedParameters: true,
          noFallthroughCasesInSwitch: true,
          noImplicitAny: true,
          strictNullChecks: true,
          baseUrl: ".",
          paths: {
            "@/*": ["src/*"]
          }
        },
        include: ["src"],
        references: [{ path: "./tsconfig.node.json" }]
      }, null, 2)
    });
    
    // 3. API Specifications
    files.push({
      path: "3-api-specifications/openapi.yaml",
      name: "openapi.yaml",
      type: "api",
      icon: Server,
      content: `openapi: 3.0.3
info:
  title: ${projectName} API
  description: Auto-generated API specification from Replay.build
  version: 1.0.0
  contact:
    name: API Support
    
servers:
  - url: http://localhost:3000/api
    description: Development server
  - url: https://api.example.com
    description: Production server

tags:
  - name: Resources
    description: Main resource operations

paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

# TODO: Add paths inferred from video analysis
# See analysis output for detected API operations

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object

security:
  - bearerAuth: []
`
    });
    
    files.push({
      path: "3-api-specifications/backend-checklist.md",
      name: "backend-checklist.md",
      type: "docs",
      icon: FileText,
      content: `# Backend Implementation Checklist

## Overview
This document outlines what your backend team needs to implement to support the generated frontend.

## Authentication
- [ ] JWT token generation
- [ ] Token validation middleware
- [ ] Refresh token mechanism
- [ ] Session management

## API Endpoints
${analysis?.businessRules ? `
Based on the analysis, implement these endpoints:

### CRUD Operations
- [ ] List resources with pagination
- [ ] Get single resource by ID
- [ ] Create new resource
- [ ] Update existing resource
- [ ] Delete resource

### Business Logic
${(analysis.businessRules as { id: string; name: string }[]).map(rule => `- [ ] ${rule.id}: ${rule.name}`).join('\n')}
` : '- [ ] Define endpoints based on your requirements'}

## Database Schema
See \`4-documentation/database-schema.md\` for suggested schema.

## Error Handling
Return errors in this format:
\`\`\`json
{
  "code": "VALIDATION_ERROR",
  "message": "Human-readable message",
  "details": { "field": "email", "error": "Invalid format" }
}
\`\`\`

## Response Formats

### Success Response (Single Item)
\`\`\`json
{
  "data": { ... },
  "meta": { "timestamp": "2024-01-01T00:00:00Z" }
}
\`\`\`

### Success Response (List)
\`\`\`json
{
  "data": [ ... ],
  "pagination": {
    "page": 1,
    "limit": 15,
    "total": 100,
    "totalPages": 7
  }
}
\`\`\`

## Security Requirements
- [ ] Input validation on all endpoints
- [ ] SQL injection prevention
- [ ] XSS prevention (escape HTML in responses)
- [ ] Rate limiting (100 req/min recommended)
- [ ] CORS configuration
- [ ] HTTPS only in production

---
Generated by Replay.build
`
    });
    
    // 4. Documentation
    files.push({
      path: "4-documentation/architecture.md",
      name: "architecture.md",
      type: "docs",
      icon: FileText,
      content: `# Architecture Overview

## Component Hierarchy

\`\`\`mermaid
graph TD
    App[App] --> Layout[Layout]
    Layout --> Header[Header]
    Layout --> Sidebar[Sidebar]
    Layout --> Main[Main Content]
    Main --> Pages[Pages]
    Pages --> Components[Feature Components]
    Components --> UI[UI Components]
\`\`\`

## Data Flow

\`\`\`mermaid
sequenceDiagram
    participant U as User
    participant C as Component
    participant H as Hook
    participant A as API Client
    participant S as Server

    U->>C: Interaction
    C->>H: Call hook
    H->>A: API request
    A->>S: HTTP request
    S-->>A: Response
    A-->>H: Processed data
    H-->>C: State update
    C-->>U: UI update
\`\`\`

## State Management

- **Server State**: React Query for API data caching
- **UI State**: React useState for local component state
- **Form State**: Controlled components with validation

## File Structure

\`\`\`
src/
├── components/
│   ├── ui/           # Reusable UI components (buttons, inputs, etc.)
│   └── features/     # Feature-specific components
├── hooks/            # Custom React hooks
├── services/         # API client and services
├── types/            # TypeScript type definitions
├── utils/            # Helper functions
└── config/           # Configuration files
\`\`\`

---
Generated by Replay.build
`
    });
    
    // 5. Design System
    if (preset) {
      files.push({
        path: "5-design-system/design-tokens.json",
        name: "design-tokens.json",
        type: "style",
        icon: Palette,
        content: JSON.stringify({
          name: preset.name,
          industry: preset.industry,
          colors: preset.colors,
          typography: preset.typography,
          borderRadius: preset.borderRadius,
          components: preset.components,
          charts: preset.charts
        }, null, 2)
      });
      
      files.push({
        path: "5-design-system/tailwind.config.js",
        name: "tailwind.config.js",
        type: "config",
        icon: FileCode,
        content: `/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['${preset.typography.fontFamily.split("'")[1]}', 'sans-serif'],
        mono: ['${preset.typography.fontFamilyMono.split("'")[1]}', 'monospace'],
      },
      colors: {
        primary: {
          DEFAULT: '${preset.colors.light.primary}',
          foreground: '${preset.colors.light.primaryForeground}',
        },
        secondary: {
          DEFAULT: '${preset.colors.light.secondary}',
          foreground: '${preset.colors.light.secondaryForeground}',
        },
        accent: {
          DEFAULT: '${preset.colors.light.accent}',
          foreground: '${preset.colors.light.accentForeground}',
        },
        success: '${preset.colors.light.success}',
        warning: '${preset.colors.light.warning}',
        error: '${preset.colors.light.error}',
        info: '${preset.colors.light.info}',
        border: '${preset.colors.light.border}',
        ring: '${preset.colors.light.ring}',
      },
      borderRadius: {
        lg: '${preset.borderRadius.lg}',
        md: '${preset.borderRadius.md}',
        sm: '${preset.borderRadius.sm}',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
`
      });
    }
    
    // 6. Quality Assurance
    files.push({
      path: "6-quality-assurance/qa-checklist.md",
      name: "qa-checklist.md",
      type: "test",
      icon: TestTube,
      content: `# QA Checklist

## Functional Testing
- [ ] All pages load without errors
- [ ] Navigation works correctly
- [ ] Forms validate correctly
- [ ] API calls succeed
- [ ] Error states are handled
- [ ] Loading states are shown

## Accessibility Testing
- [ ] Keyboard navigation works
- [ ] Screen reader compatible
- [ ] Color contrast meets WCAG AA
- [ ] Focus states are visible
- [ ] ARIA labels are present

## Responsive Testing
- [ ] Desktop (1920x1080)
- [ ] Laptop (1366x768)
- [ ] Tablet (768x1024)
- [ ] Mobile (375x667)

## Browser Testing
- [ ] Chrome (latest)
- [ ] Firefox (latest)
- [ ] Safari (latest)
- [ ] Edge (latest)

## Performance Testing
- [ ] Page load < 3s
- [ ] No memory leaks
- [ ] Images optimized
- [ ] Code split properly

---
Generated by Replay.build
`
    });
    
    // 7. Deployment
    files.push({
      path: "7-deployment/Dockerfile",
      name: "Dockerfile",
      type: "config",
      icon: Archive,
      content: `# Build stage
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`
    });
    
    files.push({
      path: "7-deployment/docker-compose.yml",
      name: "docker-compose.yml",
      type: "config",
      icon: Archive,
      content: `version: '3.8'

services:
  frontend:
    build: ../2-source-code
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    
  # Add your backend service here
  # backend:
  #   image: your-backend-image
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - DATABASE_URL=postgres://...
`
    });
    
    return files;
  }, [projectName, generatedCode, preset, analysis]);
  
  // Export as ZIP
  const handleExportZip = async () => {
    setIsExporting(true);
    setExportProgress(0);
    
    try {
      const zip = new JSZip();
      const files = generateExportFiles();
      const totalFiles = files.length;
      
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        zip.file(file.path, file.content);
        setExportProgress(Math.round(((i + 1) / totalFiles) * 100));
        await new Promise(resolve => setTimeout(resolve, 50)); // Small delay for UX
      }
      
      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${projectName.toLowerCase().replace(/\s+/g, "-")}-replay-package.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      onExport?.("zip");
    } catch (error) {
      console.error("Export failed:", error);
    } finally {
      setIsExporting(false);
      setExportProgress(0);
    }
  };
  
  // Copy file content
  const handleCopyFile = (file: ExportFile) => {
    navigator.clipboard.writeText(file.content);
    setCopiedFile(file.path);
    setTimeout(() => setCopiedFile(null), 2000);
  };
  
  const files = generateExportFiles();
  const sections = [
    { id: "source", name: "Source Code", icon: FileCode, files: files.filter(f => f.path.startsWith("2-source")) },
    { id: "api", name: "API Specs", icon: Server, files: files.filter(f => f.path.startsWith("3-api")) },
    { id: "docs", name: "Documentation", icon: BookOpen, files: files.filter(f => f.path.startsWith("4-documentation") || f.path.startsWith("1-getting")) },
    { id: "design", name: "Design System", icon: Palette, files: files.filter(f => f.path.startsWith("5-design")) },
    { id: "qa", name: "Quality Assurance", icon: TestTube, files: files.filter(f => f.path.startsWith("6-quality")) },
    { id: "deploy", name: "Deployment", icon: Archive, files: files.filter(f => f.path.startsWith("7-deployment")) },
  ];
  
  return (
    <div className="space-y-4">
      {/* Export Button */}
      <button
        onClick={handleExportZip}
        disabled={isExporting}
        className={cn(
          "w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl",
          "bg-gradient-to-r from-[var(--accent-orange)] to-orange-600",
          "text-white font-medium text-sm",
          "hover:opacity-90 transition-all",
          "disabled:opacity-50 disabled:cursor-not-allowed"
        )}
      >
        {isExporting ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Packaging... {exportProgress}%
          </>
        ) : (
          <>
            <Download className="w-4 h-4" />
            Download Enterprise Package
          </>
        )}
      </button>
      
      {/* Progress bar */}
      <AnimatePresence>
        {isExporting && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            className="overflow-hidden"
          >
            <div className="h-1.5 bg-white/[0.05] rounded-full overflow-hidden">
              <motion.div
                className="h-full bg-gradient-to-r from-[var(--accent-orange)] to-orange-500"
                initial={{ width: 0 }}
                animate={{ width: `${exportProgress}%` }}
              />
            </div>
          </motion.div>
        )}
      </AnimatePresence>
      
      {/* Package Contents */}
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <FolderTree className="w-4 h-4 text-zinc-500" />
          <span className="text-xs font-medium text-zinc-400">Package Contents</span>
          <span className="text-[10px] text-zinc-600">({files.length} files)</span>
        </div>
        
        <div className="space-y-1">
          {sections.map((section) => (
            <div key={section.id} className="rounded-lg overflow-hidden">
              <button
                onClick={() => setExpandedSection(expandedSection === section.id ? null : section.id)}
                className={cn(
                  "w-full flex items-center justify-between px-3 py-2",
                  "bg-white/[0.02] hover:bg-white/[0.04] transition-colors",
                  expandedSection === section.id && "bg-white/[0.04]"
                )}
              >
                <div className="flex items-center gap-2">
                  <section.icon className="w-3.5 h-3.5 text-zinc-500" />
                  <span className="text-xs text-zinc-400">{section.name}</span>
                  <span className="text-[10px] text-zinc-600">({section.files.length})</span>
                </div>
                <ChevronRight className={cn(
                  "w-3.5 h-3.5 text-zinc-600 transition-transform",
                  expandedSection === section.id && "rotate-90"
                )} />
              </button>
              
              <AnimatePresence>
                {expandedSection === section.id && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: "auto" }}
                    exit={{ opacity: 0, height: 0 }}
                    className="overflow-hidden"
                  >
                    <div className="p-2 space-y-1 bg-white/[0.01]">
                      {section.files.map((file) => (
                        <div
                          key={file.path}
                          className="flex items-center justify-between px-2 py-1.5 rounded-md hover:bg-white/[0.03] group"
                        >
                          <div className="flex items-center gap-2 min-w-0">
                            <file.icon className="w-3.5 h-3.5 text-zinc-600 flex-shrink-0" />
                            <span className="text-[11px] text-zinc-500 truncate">{file.path}</span>
                          </div>
                          <button
                            onClick={() => handleCopyFile(file)}
                            className="opacity-0 group-hover:opacity-100 p-1 rounded hover:bg-white/[0.05] transition-all"
                            title="Copy content"
                          >
                            {copiedFile === file.path ? (
                              <Check className="w-3 h-3 text-emerald-400" />
                            ) : (
                              <Copy className="w-3 h-3 text-zinc-500" />
                            )}
                          </button>
                        </div>
                      ))}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>
      </div>
      
      {/* Info */}
      <div className="p-3 rounded-lg bg-emerald-500/5 border border-emerald-500/10">
        <div className="flex items-center gap-2 mb-1">
          <Package className="w-3.5 h-3.5 text-emerald-400" />
          <span className="text-[11px] font-medium text-emerald-400">Enterprise Package</span>
        </div>
        <p className="text-[10px] text-emerald-300/60 leading-relaxed">
          Includes production-ready code, API specs, documentation, design tokens, 
          test scaffolds, and deployment configs. Ready for backend integration.
        </p>
      </div>
    </div>
  );
}
