import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";

export const runtime = "nodejs";
export const maxDuration = 60;

// ═══════════════════════════════════════════════════════════════════════════════
// ENTERPRISE PACKAGE DOWNLOAD
// Purpose: Bundle all generated artifacts into a downloadable ZIP
// Contents: Source code, API specs, docs, tests, design system
// ═══════════════════════════════════════════════════════════════════════════════

interface PackageRequest {
  projectName: string;
  generatedCode: string;
  scanData?: any;
  apiContracts?: any;
  debtAudit?: any;
  e2eTests?: any;
  flowDiagram?: any;
  docs?: {
    audit?: any;
    contracts?: any;
    qa?: any;
    handoff?: any;
  };
}

function generateReadme(projectName: string, scanData: any): string {
  const menuCount = scanData?.ui?.navigation?.sidebar?.items?.length || 0;
  const metricCount = scanData?.data?.metrics?.length || 0;
  const chartCount = scanData?.data?.charts?.length || 0;
  const tableCount = scanData?.data?.tables?.length || 0;

  return `# ${projectName}

## 🚀 Reconstructed by Replay.build

This project was automatically reconstructed from a legacy UI recording using AI-powered visual analysis.

### 📊 Extraction Summary

| Component | Count |
|-----------|-------|
| Menu Items | ${menuCount} |
| Metric Cards | ${metricCount} |
| Charts | ${chartCount} |
| Data Tables | ${tableCount} |

### 📁 Package Contents

\`\`\`
${projectName}/
├── src/
│   └── index.html          # Main application (React + Tailwind)
├── docs/
│   ├── AUDIT.md            # Technical debt audit
│   ├── API_SPEC.yaml       # OpenAPI/Swagger specification
│   ├── MIGRATION.md        # Migration guide
│   └── ARCHITECTURE.md     # System architecture
├── tests/
│   ├── playwright/
│   │   └── *.spec.ts       # Playwright E2E tests
│   └── cypress/
│       └── *.cy.ts         # Cypress E2E tests
├── design-system/
│   ├── tokens.json         # Design tokens
│   └── components.md       # Component inventory
├── package.json
├── tsconfig.json
└── README.md
\`\`\`

### 🛠️ Quick Start

1. **Install dependencies:**
   \`\`\`bash
   npm install
   \`\`\`

2. **Run development server:**
   \`\`\`bash
   npm run dev
   \`\`\`

3. **Run tests:**
   \`\`\`bash
   npm run test:e2e
   \`\`\`

### 📋 Technology Stack

- **Frontend:** React 18 + Tailwind CSS
- **Charts:** Recharts
- **Icons:** Lucide React
- **Testing:** Playwright + Cypress

### 🔗 Backend Integration

See \`docs/API_SPEC.yaml\` for the inferred API contracts.
Your backend team can implement these endpoints to connect the frontend.

### 📝 License

Proprietary - Generated by Replay.build for enterprise migration.

---

*Generated on ${new Date().toISOString()}*
`;
}

function generatePackageJson(projectName: string): string {
  const safeName = projectName.toLowerCase().replace(/[^a-z0-9-]/g, '-');
  return JSON.stringify({
    "name": safeName,
    "version": "1.0.0",
    "description": `Reconstructed UI from legacy system - ${projectName}`,
    "scripts": {
      "dev": "npx serve src",
      "test:e2e": "npx playwright test",
      "test:cypress": "npx cypress run"
    },
    "dependencies": {
      "react": "^18.2.0",
      "react-dom": "^18.2.0",
      "recharts": "^2.12.7",
      "lucide-react": "^0.400.0"
    },
    "devDependencies": {
      "@playwright/test": "^1.40.0",
      "cypress": "^13.6.0",
      "typescript": "^5.3.0"
    }
  }, null, 2);
}

function generateTsConfig(): string {
  return JSON.stringify({
    "compilerOptions": {
      "target": "ES2020",
      "lib": ["ES2020", "DOM", "DOM.Iterable"],
      "module": "ESNext",
      "skipLibCheck": true,
      "moduleResolution": "bundler",
      "allowImportingTsExtensions": true,
      "resolveJsonModule": true,
      "isolatedModules": true,
      "noEmit": true,
      "jsx": "react-jsx",
      "strict": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "noFallthroughCasesInSwitch": true
    },
    "include": ["src", "tests"]
  }, null, 2);
}

function generateMigrationGuide(projectName: string, scanData: any): string {
  return `# Migration Guide: ${projectName}

## Overview

This document provides step-by-step instructions for integrating the reconstructed frontend with your existing backend systems.

## Phase 1: Frontend Deployment

### 1.1 Environment Setup

\`\`\`bash
# Clone the repository
git clone <your-repo-url>
cd ${projectName.toLowerCase().replace(/\s+/g, '-')}

# Install dependencies
npm install

# Start development server
npm run dev
\`\`\`

### 1.2 Configuration

Update the API base URL in \`src/config.ts\`:

\`\`\`typescript
export const API_BASE_URL = process.env.REACT_APP_API_URL || 'https://api.your-domain.com/v1';
\`\`\`

## Phase 2: Backend Integration

### 2.1 API Endpoints

Refer to \`docs/API_SPEC.yaml\` for the complete API specification.

**Required Endpoints:**
${scanData?.data?.tables?.map((t: any, i: number) => `- GET /api/${t.title?.toLowerCase().replace(/\s+/g, '-') || `resource-${i}`}`).join('\n') || '- See API_SPEC.yaml'}

### 2.2 Data Format

Ensure your API returns data in the expected format:

\`\`\`json
{
  "data": [...],
  "pagination": {
    "page": 1,
    "limit": 10,
    "total": 100
  }
}
\`\`\`

## Phase 3: Testing

### 3.1 Run E2E Tests

\`\`\`bash
# Playwright
npm run test:e2e

# Cypress
npm run test:cypress
\`\`\`

### 3.2 Visual Regression Testing

Compare screenshots against the original legacy UI recording.

## Phase 4: Go Live

### 4.1 Checklist

- [ ] All API endpoints implemented
- [ ] E2E tests passing
- [ ] Visual regression tests passing
- [ ] Performance benchmarks met
- [ ] Security audit completed
- [ ] Accessibility audit completed

### 4.2 Rollout Strategy

1. **Staging:** Deploy to staging environment
2. **UAT:** User acceptance testing with key stakeholders
3. **Canary:** 5% traffic to new frontend
4. **Gradual:** Increase to 25%, 50%, 100%

## Support

For issues with the generated code, contact Replay.build support.

---

*Generated by Replay.build Enterprise Package*
`;
}

export async function POST(request: NextRequest) {
  try {
    const body: PackageRequest = await request.json();
    const { 
      projectName, 
      generatedCode, 
      scanData, 
      apiContracts, 
      debtAudit, 
      e2eTests,
      flowDiagram,
      docs 
    } = body;

    if (!projectName || !generatedCode) {
      return NextResponse.json(
        { error: "Project name and generated code required" },
        { status: 400 }
      );
    }

    console.log("[Enterprise-Package] Creating ZIP for:", projectName);

    const zip = new JSZip();
    const safeProjectName = projectName.replace(/[^a-zA-Z0-9-_\s]/g, '').trim();

    // Root folder
    const root = zip.folder(safeProjectName);
    if (!root) throw new Error("Failed to create root folder");

    // ═══════════════════════════════════════════════════════════════
    // SOURCE CODE
    // ═══════════════════════════════════════════════════════════════
    const src = root.folder("src");
    src?.file("index.html", generatedCode);

    // ═══════════════════════════════════════════════════════════════
    // DOCUMENTATION
    // ═══════════════════════════════════════════════════════════════
    const docsFolder = root.folder("docs");
    
    // README
    root.file("README.md", generateReadme(safeProjectName, scanData));
    
    // Migration Guide
    docsFolder?.file("MIGRATION.md", generateMigrationGuide(safeProjectName, scanData));
    
    // API Specification
    if (apiContracts) {
      docsFolder?.file("API_SPEC.yaml", `# OpenAPI Specification\n# Generated by Replay.build\n\n${JSON.stringify(apiContracts, null, 2)}`);
      docsFolder?.file("API_SPEC.json", JSON.stringify(apiContracts, null, 2));
    }
    
    // Debt Audit
    if (debtAudit) {
      docsFolder?.file("DEBT_AUDIT.json", JSON.stringify(debtAudit, null, 2));
      docsFolder?.file("DEBT_AUDIT.md", `# Technical Debt Audit\n\n## Summary\n\n- Modernization Score: ${debtAudit.meta?.modernizationScore || 'N/A'}%\n- Debt Reduction: ${debtAudit.meta?.debtReductionPercentage || 'N/A'}\n\n## Details\n\n\`\`\`json\n${JSON.stringify(debtAudit, null, 2)}\n\`\`\``);
    }
    
    // Architecture (from flow diagram)
    if (flowDiagram) {
      docsFolder?.file("ARCHITECTURE.md", `# System Architecture\n\n## Process Flow\n\n\`\`\`mermaid\n${flowDiagram.processArchitecture?.mermaid || 'graph TD\nA[Start] --> B[End]'}\n\`\`\`\n\n## Full Data\n\n\`\`\`json\n${JSON.stringify(flowDiagram, null, 2)}\n\`\`\``);
    }
    
    // Enterprise docs
    if (docs) {
      if (docs.audit) docsFolder?.file("audit.json", JSON.stringify(docs.audit, null, 2));
      if (docs.contracts) docsFolder?.file("contracts.json", JSON.stringify(docs.contracts, null, 2));
      if (docs.qa) docsFolder?.file("qa.json", JSON.stringify(docs.qa, null, 2));
      if (docs.handoff) docsFolder?.file("handoff.json", JSON.stringify(docs.handoff, null, 2));
    }

    // ═══════════════════════════════════════════════════════════════
    // TESTS
    // ═══════════════════════════════════════════════════════════════
    const testsFolder = root.folder("tests");
    
    if (e2eTests) {
      // Playwright tests
      const playwrightFolder = testsFolder?.folder("playwright");
      if (e2eTests.playwright?.tests) {
        e2eTests.playwright.tests.forEach((test: any, index: number) => {
          const fileName = test.file || `test-${index + 1}.spec.ts`;
          playwrightFolder?.file(fileName, test.code || `// ${test.name}\n// TODO: Implement test`);
        });
      }
      if (e2eTests.playwright?.config) {
        playwrightFolder?.file("playwright.config.ts", e2eTests.playwright.config);
      }
      
      // Cypress tests
      const cypressFolder = testsFolder?.folder("cypress");
      if (e2eTests.cypress?.tests) {
        e2eTests.cypress.tests.forEach((test: any, index: number) => {
          const fileName = test.file || `test-${index + 1}.cy.ts`;
          cypressFolder?.file(fileName, test.code || `// ${test.name}\n// TODO: Implement test`);
        });
      }
      if (e2eTests.cypress?.config) {
        cypressFolder?.file("cypress.config.ts", e2eTests.cypress.config);
      }
    }

    // ═══════════════════════════════════════════════════════════════
    // DESIGN SYSTEM
    // ═══════════════════════════════════════════════════════════════
    const designFolder = root.folder("design-system");
    
    if (scanData?.ui?.colors) {
      designFolder?.file("tokens.json", JSON.stringify({
        colors: scanData.ui.colors,
        typography: scanData.ui.typography,
        spacing: { scale: [0, 4, 8, 12, 16, 24, 32, 48, 64] }
      }, null, 2));
    }
    
    if (debtAudit?.atomicInventory) {
      designFolder?.file("components.md", `# Component Inventory\n\n## Atoms\n${debtAudit.atomicInventory.atoms?.map((a: any) => `- **${a.name}**: ${a.usage}`).join('\n') || 'N/A'}\n\n## Molecules\n${debtAudit.atomicInventory.molecules?.map((m: any) => `- **${m.name}**: ${m.usage}`).join('\n') || 'N/A'}\n\n## Organisms\n${debtAudit.atomicInventory.organisms?.map((o: any) => `- **${o.name}**: ${o.usage}`).join('\n') || 'N/A'}`);
    }

    // ═══════════════════════════════════════════════════════════════
    // CONFIG FILES
    // ═══════════════════════════════════════════════════════════════
    root.file("package.json", generatePackageJson(safeProjectName));
    root.file("tsconfig.json", generateTsConfig());
    root.file(".gitignore", "node_modules/\ndist/\n.env\n.env.local\n");

    // ═══════════════════════════════════════════════════════════════
    // SCAN DATA (for reference)
    // ═══════════════════════════════════════════════════════════════
    if (scanData) {
      root.file("scan-data.json", JSON.stringify(scanData, null, 2));
    }

    // Generate ZIP
    const zipBuffer = await zip.generateAsync({ 
      type: "nodebuffer",
      compression: "DEFLATE",
      compressionOptions: { level: 9 }
    });

    console.log(`[Enterprise-Package] ZIP created, size: ${zipBuffer.length} bytes`);

    // Convert Buffer to Uint8Array for NextResponse compatibility
    const uint8Array = new Uint8Array(zipBuffer);

    // Return as downloadable file
    return new NextResponse(uint8Array, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${safeProjectName}-enterprise-package.zip"`,
        "Content-Length": zipBuffer.length.toString(),
      },
    });

  } catch (error: any) {
    console.error("[Enterprise-Package] Error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to create package" },
      { status: 500 }
    );
  }
}
